# Generated by Django 3.2.6 on 2023-07-27 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='current_stage',
            field=models.CharField(choices=[('Planning', 'Planing'), ('Started', 'Started'), ('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Paused', 'Paused')], max_length=55),
        ),
        migrations.AlterField(
            model_name='projects',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.employee'),
        ),
    ]
